### ISSUE TITLE
report spam messages

### ISSUE THREAD

**Issue by crayxt** [transifex/transifex#308]
Today I received a spam message from user amirabash22

there is no way to mark message a spam or report spammer user.

**Comment by nikosdion** [comment]
I am, too, receiving spam. For example http://email.transifex.com/c/eJxVTssOgyAQ_Bq51bC8CgcOvfTWj1gQldiKEYxNv75oT00mmczuZGY6a8AoTaJlFCS9UkUNE5K3jEkqWw5SQyOoC8DasuKcYx_erU8vMlpNwaDjIgglQHCoZqaN7DsHiJ3U5GnHUpbc8FvD7hX7vv-H1FtaB5zjB0tMc5UPHKKvXAIeXyEY15W7mP2W889zFp2JfEm5XKpWkqx2jn5MT8x1L04hOHTop205ir5pH0T7  This joker added a bunch of people to his organisation *without* our express consent. There is no way to report this blatantly spammy action anywhere.

Even worse, we get notifications for the threads in his organisation.

Double worse, removing oneself from an organisation is a trip in insanity: you need to go to the organisation, figure out which languages he has added you, expand the list of participants, find your name and find the Leave button. 15 minutes wasted off my life.

And to add insult to injury I still get notifications for that damned thread I didn't want to participate in, in an organisation I never asked to join. The notifications lead to a URL (see above) which I can't visit because I'm no longer a member of the organisation.

Your organisation member approval and notification system is crazy. Anyone can add anyone else in their organisation and spam them at will. If they want to be really sly about it they can add you to an organisation, start a spam thread, kick you out of the organisation and then keep on sending spam after spam message with no possibility to block this crap other than closing your Transifex account.

**Comment by glezos** [comment]
Folks, we'll discuss this internally and see if we can find a solution.
Thank you for bringing this up. We apologize for the inconvenience created.

-d

On Mon, Jul 6, 2015 at 3:29 AM, Nicholas K. Dionysopoulos <
notifications@github.com> wrote:

> I am, too, receiving spam. For example
> http://email.transifex.com/c/eJxVTssOgyAQ_Bq51bC8CgcOvfTWj1gQldiKEYxNv75oT00mmczuZGY6a8AoTaJlFCS9UkUNE5K3jEkqWw5SQyOoC8DasuKcYx_erU8vMlpNwaDjIgglQHCoZqaN7DsHiJ3U5GnHUpbc8FvD7hX7vv-H1FtaB5zjB0tMc5UPHKKvXAIeXyEY15W7mP2W889zFp2JfEm5XKpWkqx2jn5MT8x1L04hOHTop205ir5pH0T7
> This joker added a bunch of people to his organisation *without* our
> express consent. There is no way to report this blatantly spammy action
> anywhere.
>
> Even worse, we get notifications for the threads in his organisation.
>
> Double worse, removing oneself from an organisation is a trip in insanity:
> you need to go to the organisation, figure out which languages he has added
> you, expand the list of participants, find your name and find the Leave
> button. 15 minutes wasted off my life.
>
> And to add insult to injury I still get notifications for that damned
> thread I didn't want to participate in, in an organisation I never asked to
> join. The notifications lead to a URL (see above) which I can't visit
> because I'm no longer a member of the organisation.
>
> Your organisation member approval and notification system is crazy. Anyone
> can add anyone else in their organisation and spam them at will. If they
> want to be really sly about it they can add you to an organisation, start a
> spam thread, kick you out of the organisation and then keep on sending spam
> after spam message with no possibility to block this crap other than
> closing your Transifex account.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transifex/transifex/issues/308#issuecomment-118803641>
> .
>



-- 
Dimitris Glezos
Founder & CEO, Transifex
http://www.transifex.com/

**Comment by glixx** [comment]
Tx must ask "yes" before adding in team by confirmaition email.
