### ISSUE TITLE
Pagina no encontrada

### ISSUE THREAD

**Issue by guillermohaad** [transifex/transifex#368]
Recibí la siguiente notificación y cuando estro al link dice pagina no encontrada ???

Hi Guillermo haad,
You have been accepted to the team GLPI Project team for Spanish (Colombia).

**Comment by nelefth** [comment]
Hello Guillermo, 

I checked your join team request, the one you submitted using the Transifex account guillermohaad and it is still pending. That's why you are not able to access the link. 

Could you please check if you have submitted the same request using a different Transifex account?
I am asking this, since I found another user (memohaad) who already belongs to the team and has the same name as yours. 
Please also note that you can use our contact form [here](https://www.transifex.com/contact/) in order to contact Transifex Support, as we don't provide official support in this repo any more.
