### ISSUE TITLE
Page not found for opentranslators/flexicontent

### ISSUE THREAD

**Issue by pencilpete** [transifex/transifex#369]
Couldn't access the Flexicontent 3.x 2.x and 1.5.X project in opentranslators organization
Bad Link: https://www.transifex.com/opentranslators/opentranslators/opentranslators/opentranslators/

**Comment by nelefth** [comment]
@pencilpete I would like to inform you that the issue has been resolved. We apologise for any inconvenience that this may have caused you.
Please follow this link: https://www.transifex.com/opentranslators/ in order to access the organization. 

Please also note that you can use our contact form [here](https://www.transifex.com/contact/) in order to contact Transifex Support, as we don't provide official support in this repo any more.
