### ISSUE TITLE
Php arrays aren't recognized when the keyword is title-case

### ISSUE THREAD

**Issue by rimas-kudelis** [transifex/transifex#371]
When trying to upload a file of type PHP_ARRAY where the array keyword uses title case (**Array** vs array), I get the following error from the server:

> Exception: Error uploading file: No PHP array pattern was found!

Changing the uppercase "A" to "a" solves this issue, but it would be nice if your server would act smarter.

**Comment by nelefth** [comment]
@rimas-kudelis, thank you for taking the time to leave your feedback. However, in case of PHP_ARRAY the input array should be mentioned as "array" and not "Array" according to the file format's specifications.  
Please also note that you can use our contact form [here](https://www.transifex.com/contact/) in order to contact Transifex Support, as we don't provide official support in this repo anymore.
