### ISSUE TITLE
Problems with auto-update - unicode

### ISSUE THREAD

**Issue by george-silva** [transifex/transifex#372]
Hello guys from the PostGIS project.

We are having some problems with auto-updating some resources here. It worked fine until two or three days, without changes from our side. It started to fail on some unicode error in the Python side of things.

Here's the email:

```

Hi georgersilva,

We have not been able to update the source file for the resource introduction.xml.pot of the project PostGIS.

The URL we used to update the source file from was https://raw.githubusercontent.com/postgis/postgis/svn-trunk/doc/po/templates/introduction.xml.pot.

The exact error we encountered was:

'ascii' codec can't encode character u'\xe9' in position 4100: ordinal not in range(128)
--
The Transifex Robot
```

The file in question has non-ascii characters in them. Can you guys help? Looks like a change on your side, since these emails started to come a few days ago and the last change we had as around 20 days ago.

Thanks!

**Comment by nelefth** [comment]
Hi @george-silva. 

Thank you for taking the time to report this. I would like to inform you that we are already aware of this issue. Our software engineers will handle this as soon as possible.
We really apologise for any inconvenience that this may have caused you.

Thank you for your patience and understanding. 

Please also note that you can use our contact form [here](https://www.transifex.com/contact/) in order to contact Transifex Support, as we don't provide official support in this repo anymore.
