### ISSUE TITLE
Delete language is not posible or not is easy

### ISSUE THREAD

**Issue by moylop260** [transifex/transifex#375]
I'm trying delete a particular language but is don't find a option to delete it from webpage.

I spent 1 hour without find the option to delete it.
I go to my dashboard:
 - https://www.transifex.com/Vauxoo/

Choose `Go to your teams & languages`

Choose a team with that language.
I choose `delete`.
But I saw a popup message where I can't delete this team because have the project assigned.
I re-assign the project
Delete the team.

But the language is not deleted.

What is wrong with my process or the webpage?

I saw other question similar:
 - http://stackoverflow.com/questions/28427555/how-to-remove-languages-in-transifex

Is a opportunity to change the GUI to better UX?
Or I'm a bad user

**Comment by nelefth** [comment]
@moylop260 I assume that you are looking for a way to remove a target language from a project of yours. 

If this is your case, then you need to visit the project's languages page and use the "Edit languages" button as follows: http://www.screencast.com/t/vf3xUcUcMhr

However, if you want to remove a target language group, this can only be done via teams page as you described above. 

Please let me know if this helps or if I have misunderstood your case. 

Please also note that you can use our contact form [here](https://www.transifex.com/contact/) in order to contact Transifex Support, as we don't provide official support in this repo anymore.

**Comment by moylop260** [comment]
Thanks for reply
I'll check it
